const express = require("express")

const getCountryInfo = require("./subToolApi/getCountryInfo")
const getCurrentDate = require("./subToolApi/getCurrentDate")
const getCurrentTime = require("./subToolApi/getCurrentTime")
const tool = require("../tool")
const getIpAddress = require("./subToolApi/getIpAddress")
const getKeyPair = require("./subToolApi/getKeyPair")
const getMd5 = require("./subToolApi/getMd5")
const getRandomPassword = require("./subToolApi/getRandomPassword")
const getRandomString = require("./subToolApi/getRandomString")
const getRandomUser = require("./subToolApi/getRandomUser")
const testHttpRequest = require("./subToolApi/testHttpRequest")
const translate = require("./subToolApi/translate")

const toolApi = express.Router()

toolApi.use("/api", getCountryInfo)
toolApi.use("/api", getCurrentDate)
toolApi.use("/api", getCurrentTime)
toolApi.use("/api", getIpAddress)
toolApi.use("/api", getKeyPair)
toolApi.use("/api", getMd5)
toolApi.use("/api", getRandomPassword)
toolApi.use("/api", getRandomString)
toolApi.use("/api", getRandomUser)
toolApi.use("/api", testHttpRequest)
toolApi.use("/api", translate)

module.exports = toolApi